clusters:
  - name: cluster-2
    prometheusUrl: http://localhost:9090

costs:
  cpuCore: 10
  memoryGb: 20
  storageGb: 5

oidc:
  enabled: false
  issuer: ${KEYCLOAK_ISSUER}
  clientId: ${KEYCLOAK_CLIENT_ID}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET}
  adminGroup: admin
  viewerGroup: viewer
