clusters:
  - name: cluster-1
    prometheusUrl: http://localhost:8080

costs:
  cpuCore: 10
  memoryGb: 20
  storageGb: 5

oidc:
  enabled: false
  issuer: ${OIDC_ISSUER}
  clientId: ${OIDC_CLIENT_ID}
  clientSecret: ${OIDC_CLIENT_SECRET}
  adminGroup: admin
  viewerGroup: viewer

sharednamespaces:
  - kube-system
