apiVersion: v1
kind: Pod
metadata:
  name: pending-pod
spec:
  containers:
  - name: pending-pod
    image: ubuntu:24.04
    command: ["sleep", "infinity"]
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: this-node-does-not-exist