image:
  repository: ghcr.io/fabiotavernini/spendemon
  tag: "0.0.2"
  pullPolicy: IfNotPresent
  imagePullSecret: "ghcr-login-secret"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  hosts:
    - host: spendemon.local
      paths:
        - path: /
          pathType: Prefix

gateway:
  enabled: true

  parentRefs:
    - name: cloudflare-gw
      namespace: cloudflare-gateway

  hosts:
    - spendemon.tavernini.online

  rules:
    - matches:
        - path: /
          pathType: PathPrefix

resources: {}

settings:
  mountPath: "/app/settings.yaml"
  clusters:
    - name: cluster-1
      prometheusUrl: http://prometheus-service.prometheus.svc.cluster.local:80
    # - name: cluster-2
    #   prometheusUrl: http://localhost:9090
  costs:
    cpuCore: 10
    memoryGb: 20
    storageGb: 5
  oidc:
    enabled: false
    adminGroup: admin
    viewerGroup: viewer
    secretRef:
      name: ""
      issuerKey: issuer
      clientIdKey: clientId
      clientSecretKey: clientSecret
