image:
  repository: ghcr.io/FabioTavernini/spendemon
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  hosts:
    - host: spendemon.local
      paths:
        - path: /
          pathType: Prefix

resources: {}