image:
  repository: ghcr.io/fabiotavernini/spendemon
  tag: "latest"
  pullPolicy: IfNotPresent
  imagePullSecret: ""

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  hosts:
    - host: spendemon.domain.com
      paths:
        - path: /
          pathType: Prefix

gateway:
  enabled: false

  parentRefs:
    - name: yourgateway
      namespace: gateway-namespace

  hosts:
    - spendemon.domain.com

  rules:
    - matches:
        - path: /
          pathType: PathPrefix

resources: {}

persistence:
  mountPath: /data
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClassName: ""

settings:
  clusters:
    - name: cluster-1
      prometheusUrl: http://prometheus-service.prometheus.svc.cluster.local:80
    # - name: cluster-2
    #   prometheusUrl: http://localhost:9090
  costs:
    cpuCore: 10
    memoryGb: 20
    storageGb: 5
  ha:
    enabled: false
  sharednamespaces:
    - kube-system
  oidc:
    enabled: false
    debug: false
    extraScopes: []
    url: ""
    nextAuthUrl: ""
    adminGroup: admin
    viewerGroup: viewer
    secretRef:
      name: ""
      issuerKey: issuer
      clientIdKey: clientId
      clientSecretKey: clientSecret
      nextAuthSecretKey: nextauthSecret
